server:
  port: 14080

#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/resilience4j/resilience4j-spring-cloud2-demo
#          default-label: config

#spring.profiles.active: native
#spring.cloud.config.server.native.searchLocations: file:///${user.home}/Documents/projects/turing/config
spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
